import { Timestamp } from 'firebase/firestore'
import type { UserDoc, Pin, ListingPin, SoldPin, StoryPin, ReelPin, LivePin, OpenHousePin } from '@/lib/types'

const now = Timestamp.now()
const hours = (h: number) => Timestamp.fromMillis(Date.now() + h * 3600_000)
const daysAgo = (d: number) => Timestamp.fromMillis(Date.now() - d * 86400_000)

// ── Mock Agents ──

export const MOCK_AGENTS: UserDoc[] = [
  {
    uid: 'agent-carolina',
    email: 'carolina@reelst.co',
    role: 'agent',
    agentType: 'agent',
    createdAt: daysAgo(90),
    username: 'carolina',
    displayName: 'Carolina Reyes',
    photoURL: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=200&h=200&fit=crop&crop=face',
    bio: 'Miami luxury specialist. Helping families find their dream home in South Florida.',
    brokerage: 'Compass',
    licenseNumber: 'SL3489201',
    licenseState: 'FL',
    platforms: [
      { id: 'instagram', username: 'carolina.reyes.re' },
      { id: 'tiktok', username: 'carolinasellsmiami' },
      { id: 'zillow', username: 'carolina-reyes' },
    ],
    followerCount: 1247,
    followingCount: 83,
    onboardingComplete: true,
    onboardingStep: 8,
    setupPercent: 90,
  },
  {
    uid: 'agent-david',
    email: 'david@reelst.co',
    role: 'agent',
    agentType: 'agent',
    createdAt: daysAgo(60),
    username: 'david',
    displayName: 'David Hartman',
    photoURL: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=200&h=200&fit=crop&crop=face',
    bio: 'Brickell & Downtown Miami condos. Your skyline expert.',
    brokerage: 'Douglas Elliman',
    licenseNumber: 'SL3501882',
    licenseState: 'FL',
    platforms: [
      { id: 'instagram', username: 'davidhartman_re' },
      { id: 'youtube', username: 'DavidSellsMiami' },
    ],
    followerCount: 834,
    followingCount: 45,
    onboardingComplete: true,
    onboardingStep: 8,
    setupPercent: 85,
  },
  {
    uid: 'agent-lucia',
    email: 'lucia@reelst.co',
    role: 'agent',
    agentType: 'agent',
    createdAt: daysAgo(45),
    username: 'lucia',
    displayName: 'Lucia Fernandez',
    photoURL: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=200&h=200&fit=crop&crop=face',
    bio: 'Coral Gables & Coconut Grove. Architecture lover, neighborhood storyteller.',
    brokerage: 'The Keyes Company',
    licenseNumber: 'SL3612003',
    licenseState: 'FL',
    platforms: [
      { id: 'instagram', username: 'lucia.homes' },
      { id: 'tiktok', username: 'luciafernandez' },
    ],
    followerCount: 2103,
    followingCount: 112,
    onboardingComplete: true,
    onboardingStep: 8,
    setupPercent: 100,
  },
]

export const MOCK_CURRENT_USER: UserDoc = {
  uid: 'agent-mau',
  email: 'mau@reelst.co',
  role: 'agent',
  agentType: 'agent',
  createdAt: daysAgo(1),
  username: 'mau',
  displayName: 'Mau Romano',
  photoURL: null,
  bio: '',
  brokerage: null,
  licenseNumber: null,
  licenseState: null,
  platforms: [],
  followerCount: 0,
  followingCount: 0,
  onboardingComplete: true,
  onboardingStep: 8,
  setupPercent: 35,
}

// ── Mock Pins for Carolina ──

export const MOCK_PINS_CAROLINA: Pin[] = [
  // Listings
  {
    id: 'pin-1',
    agentId: 'agent-carolina',
    type: 'listing',
    coordinates: { lat: 25.7617, lng: -80.1918 },
    address: '1000 Brickell Plaza, Miami, FL 33131',
    neighborhoodId: 'brickell',
    geohash: 'dhwfhx',
    enabled: true,
    createdAt: daysAgo(14),
    updatedAt: daysAgo(14),
    views: 3842,
    taps: 287,
    saves: 94,
    price: 1350000,
    beds: 3,
    baths: 2,
    sqft: 1850,
    heroPhotoUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop',
    photos: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=800&h=600&fit=crop',
    ],
    description: 'Stunning waterfront condo in the heart of Brickell. Floor-to-ceiling windows with panoramic bay views. Italian kitchen, marble baths, private balcony.',
    status: 'active',
  } as ListingPin,
  {
    id: 'pin-2',
    agentId: 'agent-carolina',
    type: 'listing',
    coordinates: { lat: 25.7906, lng: -80.1300 },
    address: '5025 Collins Ave, Miami Beach, FL 33140',
    neighborhoodId: 'south-beach',
    geohash: 'dhwfj2',
    enabled: true,
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
    views: 2156,
    taps: 198,
    saves: 67,
    price: 2800000,
    beds: 4,
    baths: 3,
    sqft: 2400,
    heroPhotoUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop',
    photos: [
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&h=600&fit=crop',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?w=800&h=600&fit=crop',
    ],
    description: 'Oceanfront penthouse with private rooftop terrace. Direct beach access, resort-style amenities.',
    status: 'active',
  } as ListingPin,
  {
    id: 'pin-3',
    agentId: 'agent-carolina',
    type: 'listing',
    coordinates: { lat: 25.7281, lng: -80.2380 },
    address: '3401 SW 22nd St, Coral Gables, FL 33145',
    neighborhoodId: 'coral-gables',
    geohash: 'dhwf5q',
    enabled: true,
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
    views: 987,
    taps: 76,
    saves: 23,
    price: 890000,
    beds: 3,
    baths: 2,
    sqft: 1600,
    heroPhotoUrl: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop',
    photos: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=800&h=600&fit=crop',
    ],
    description: 'Charming Mediterranean home in the heart of Coral Gables. Updated kitchen, lush tropical landscaping, 2-car garage.',
    status: 'active',
  } as ListingPin,

  // Sold
  {
    id: 'pin-4',
    agentId: 'agent-carolina',
    type: 'sold',
    coordinates: { lat: 25.7508, lng: -80.2618 },
    address: '2800 Coconut Ave, Coconut Grove, FL 33133',
    neighborhoodId: 'coconut-grove',
    geohash: 'dhwf4r',
    enabled: true,
    createdAt: daysAgo(30),
    updatedAt: daysAgo(5),
    views: 1456,
    taps: 112,
    saves: 38,
    soldPrice: 1150000,
    soldDate: daysAgo(5),
    originalPrice: 1200000,
    heroPhotoUrl: 'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&h=600&fit=crop',
    photos: [
      'https://images.unsplash.com/photo-1583608205776-bfd35f0d9f83?w=800&h=600&fit=crop',
    ],
  } as SoldPin,
  {
    id: 'pin-5',
    agentId: 'agent-carolina',
    type: 'sold',
    coordinates: { lat: 25.7695, lng: -80.1936 },
    address: '801 S Miami Ave, Miami, FL 33130',
    neighborhoodId: 'brickell',
    geohash: 'dhwfhx',
    enabled: true,
    createdAt: daysAgo(45),
    updatedAt: daysAgo(20),
    views: 2891,
    taps: 234,
    saves: 51,
    soldPrice: 725000,
    soldDate: daysAgo(20),
    originalPrice: 749000,
    heroPhotoUrl: 'https://images.unsplash.com/photo-1567496898669-ee935f5f647a?w=800&h=600&fit=crop',
    photos: [
      'https://images.unsplash.com/photo-1567496898669-ee935f5f647a?w=800&h=600&fit=crop',
    ],
  } as SoldPin,

  // Stories
  {
    id: 'pin-6',
    agentId: 'agent-carolina',
    type: 'story',
    coordinates: { lat: 25.7743, lng: -80.1937 },
    address: 'Wynwood Arts District, Miami, FL',
    neighborhoodId: 'wynwood',
    geohash: 'dhwfjx',
    enabled: true,
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
    views: 482,
    taps: 67,
    saves: 12,
    mediaUrl: 'https://images.unsplash.com/photo-1533158326339-7f3cf2404354?w=600&h=1000&fit=crop',
    mediaType: 'image',
    caption: 'Sunday vibes in Wynwood. This neighborhood keeps getting better — new gallery opening next week!',
    expiresAt: hours(18),
  } as StoryPin,
  {
    id: 'pin-7',
    agentId: 'agent-carolina',
    type: 'story',
    coordinates: { lat: 25.7617, lng: -80.1918 },
    address: 'Brickell City Centre, Miami, FL',
    neighborhoodId: 'brickell',
    geohash: 'dhwfhx',
    enabled: true,
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
    views: 318,
    taps: 41,
    saves: 8,
    mediaUrl: 'https://images.unsplash.com/photo-1514565131-fce0801e5785?w=600&h=1000&fit=crop',
    mediaType: 'image',
    caption: 'Just showed this incredible unit to a family relocating from NYC. They loved the skyline views!',
    expiresAt: hours(12),
  } as StoryPin,
  {
    id: 'pin-8',
    agentId: 'agent-carolina',
    type: 'story',
    coordinates: { lat: 25.7281, lng: -80.2380 },
    address: 'Coral Gables, FL',
    neighborhoodId: 'coral-gables',
    geohash: 'dhwf5q',
    enabled: true,
    createdAt: daysAgo(0),
    updatedAt: daysAgo(0),
    views: 156,
    taps: 22,
    saves: 5,
    mediaUrl: 'https://images.unsplash.com/photo-1600047509807-ba8f99d2cdde?w=600&h=1000&fit=crop',
    mediaType: 'image',
    caption: 'New listing coming soon in Coral Gables. DM me for early access.',
    expiresAt: hours(6),
  } as StoryPin,

  // Reels
  {
    id: 'pin-9',
    agentId: 'agent-carolina',
    type: 'reel',
    coordinates: { lat: 25.7520, lng: -80.1340 },
    address: 'Key Biscayne, FL 33149',
    neighborhoodId: 'key-biscayne',
    geohash: 'dhwf3m',
    enabled: true,
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
    views: 12800,
    taps: 890,
    saves: 234,
    mediaUrl: '',
    thumbnailUrl: 'https://images.unsplash.com/photo-1600573472556-e636c2acda9e?w=400&h=700&fit=crop',
    duration: 45,
    caption: 'Tour this $3.2M Key Biscayne waterfront home with me. Wait till you see the backyard...',
  } as ReelPin,
  {
    id: 'pin-10',
    agentId: 'agent-carolina',
    type: 'reel',
    coordinates: { lat: 25.7860, lng: -80.1290 },
    address: 'South Beach, Miami Beach, FL',
    neighborhoodId: 'south-beach',
    geohash: 'dhwfj2',
    enabled: true,
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
    views: 8400,
    taps: 620,
    saves: 189,
    mediaUrl: '',
    thumbnailUrl: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=400&h=700&fit=crop',
    duration: 30,
    caption: '5 things I wish I knew before buying in South Beach. Number 3 will surprise you.',
  } as ReelPin,

  // Open House
  {
    id: 'pin-11',
    agentId: 'agent-carolina',
    type: 'open_house',
    coordinates: { lat: 25.7450, lng: -80.2200 },
    address: '1520 Alhambra Cir, Coral Gables, FL 33134',
    neighborhoodId: 'coral-gables',
    geohash: 'dhwf5q',
    enabled: true,
    createdAt: daysAgo(2),
    updatedAt: daysAgo(2),
    views: 567,
    taps: 89,
    saves: 34,
    listingPrice: 975000,
    startTime: hours(2),
    endTime: hours(5),
    heroPhotoUrl: 'https://images.unsplash.com/photo-1605276374104-dee2a0ed3cd6?w=800&h=600&fit=crop',
  } as OpenHousePin,

  // Live
  {
    id: 'pin-12',
    agentId: 'agent-carolina',
    type: 'live',
    coordinates: { lat: 25.7580, lng: -80.1900 },
    address: 'Brickell Heights, Miami, FL',
    neighborhoodId: 'brickell',
    geohash: 'dhwfhx',
    enabled: true,
    createdAt: now,
    updatedAt: now,
    views: 43,
    taps: 43,
    saves: 2,
    streamUrl: '',
    viewerCount: 23,
    startedAt: now,
    title: 'Live tour: New penthouse listing in Brickell Heights!',
  } as LivePin,
]

// ── Helpers ──

export function getMockAgent(username: string): UserDoc | null {
  return MOCK_AGENTS.find((a) => a.username === username) || null
}

export function getMockPins(agentId: string): Pin[] {
  if (agentId === 'agent-carolina') return MOCK_PINS_CAROLINA
  return []
}
